### ISSUE TITLE
Select target zones

### ISSUE THREAD

**Issue by saildeep** [saildeep/SmmCaptureEvolve.Altis#34]
As it is hard to determine good target zones algorithmically I propose we let this decide the player. My idea is to add an action to the tent "Vote next target zone". As soon as the player activates that action the map opens and he can click anywhere on the map. His vote will be shown on his personal map via a local marker. The position he selected is attached as a player variable. If he never voted, this is unset. When the HC selects a new target zone for a target, it gets all the target positions of the players in the faction and foreach position selects the neareast candidate zone. Using this a majority vote is performed on which zone should be attacked next. We may think of showing other players the votes of each player.  Comments are welcome.

**Comment by hanibalv2** [comment]
Like I would implement it:
- All neighboring zones can be selected. 
- For each zone, the loot that can be obtained is visible (even the loot of other classes,if possible).
- Every user has _x votes (based on max tasks). 
- As soon as the first user casts his vote, a timer starts to run (for example 5 minutes). 
- The more users have cast their votes, the less remaining time is over (if one of them is Afk, for example).
- There must be an election, otherwise there is no active target zone.
- A choice can only be made if a task becomes free (i. e. if you have conquered a zone).
- An election can only be initiated at a tent. Once an election has been started, all members of the faction can vote, regardless of where they are.

Options:
- select a zone for a upcoming voting. 

I like the idea to select a zone via the map.

**Comment by saildeep** [comment]
@hanibalv2 i think multiple votes per user would just confuse people. Previewing the loot would be a nice option, but hard to implement to run smooth. Voting anywhere is a bit problematic due to the nature of addAction. I intended that each user can give a "direction" where he wants to go, so he doesn't need to vote after each zone was conquered.

**Comment by hanibalv2** [comment]
Is it possible to use the build in vote system? 
Like "Press F1 and select a Zone you would like to attack. Remaining vote-time: 5:00 min".



> I intended that each user can give a "direction" where he wants to go, so he doesn't need to vote after each zone was conquered.

Yhea this I mean by: 
> select a zone for a upcoming voting.

**Comment by saildeep** [comment]
No we can't utilize the votekick system. I think we should minimize the user engagement on this. The best option in my opinion is, if the user needs to select a "direction" once per session and then doesn't need to care anymore.
