### ISSUE TITLE
Add tracking marker for AI units leaving their zone

### ISSUE THREAD

**Issue by saildeep** [saildeep/SmmCaptureEvolve.Altis#7]
A Common Problem is, that the AI leaves the zone range and is not locatable by the player. To prevent this, all AI units leaving a Zone should be displayed on the Map with a marker. The biggest problem here is, keeping the impact on performance low.

**Comment by hanibalv2** [comment]
i work on a "buy zone" action at the tent.

i forced to use this formula :

_price = (UnitsInZone x 100 x ZoneSize) /(time past since on_zone_enter is triggerd)

**Comment by hanibalv2** [comment]
if a zone is bought  the remaining Units will be deleted.

The time value will guarantee that the action get functional and will not be abused.

**Comment by hanibalv2** [comment]
in the case that i am to stupid for advance math i decided to take the advice from Fezward.

the Zone is only purchasable if 20 percent of the Units + vehicles left. 

so the formula then is something like that:

if (20percent) then{
_price = (leftUnits*1000 + leftVehicles*10000)/(time past since on_zone_enter is triggerd)
}

which give out a nice low but accurate price. (between 1000 and 500 for a small zone if 10 percent left)

**Comment by saildeep** [comment]
Please open a new ticket for this. I think it should not depend on the time passes as this may force the player to wait for no reason. I think counting the units for the zone price may be sufficient.

**Comment by justcallmeduncan** [comment]
the price could be exponentially to the number of living units

**Comment by hanibalv2** [comment]
new issue for buy zone function
